## Lists, Dictionaries and Sets in Python

## Part 1

### Lists in Python

Sequences in Python are data structures that hold objects in an ordered array. Now, we will work on Lists, the most common sequence data types in Python.

In [93]:
#Example 
l1 = ['learning', "Python", 'is fun?', True]
print(l1)

['learning', 'Python', 'is fun?', True]


List can also be created by using list() function. 

In [94]:
#Example
l2 = list(("learning", "for", "life", True))
print(l2)

['learning', 'for', 'life', True]


Adding to an existing list

### Question 1

Add 10 to list l1 given above.

[ **Hint: ** Use **append** ]

In [95]:
#Adding 10 to the list
l1.append(10)

print(l1)

['learning', 'Python', 'is fun?', True, 10]


Removing from an existing list

### Question 2

Remove 10 from l1.

[ **Hint:** Use **remove**]

In [96]:
#Removing the element 10 from the list
l1.remove(10)
print(l1)

['learning', 'Python', 'is fun?', True]


Joining 2 lists

### Question 3

[ **Hint: ** Use **+** operator or **extend**]

In [25]:
l1 = ['learning', "Python", 'is fun?', True]
l2 = list(("learning", "for", "life", True))

In [97]:
#Joining list by using + operator
joinedlist = l1+l2
print(joinedlist)

['learning', 'Python', 'is fun?', True, 'learning', 'for', 'life', True]


Number List

### Question 4

Find Range and Mean of l3.

l3 = [2,4,6,8]

[ **Hint: ** Use **len(),sum(), min(), max()** functions ]
 
If you want to use standard functions like mean & range, you have to import them from numpy else you can calculate them the traditional way using formulas

In [98]:
#Range is max - min
#Mean is average values

l3=[2,4,6,8]
print(l3)
print("Range : ", max(l3) - min(l3))

[2, 4, 6, 8]
Range :  6


In [99]:
print(" Mean : ", sum(l3)/len(l3))

 Mean :  5.0


Count the occurances of an element in a given list.

### Question 5
Append the given sequence of numbers to l3 (given above) 0,1,3,3,5,5,7,9. Count the occurences of 5 in l3.

[ **Hint: ** Use ** + operator to add multiple elements in the array and count() function to print the occurences**]

In [100]:
#Adding new values to the existing list
newseq = [0,1,3,3,5,5,7,9]
print("newlist",newseq)
l3 = l3 + newseq
print("updated l3",l3)
print("Count of 5s : ",l3.count(5))

newlist [0, 1, 3, 3, 5, 5, 7, 9]
updated l3 [2, 4, 6, 8, 0, 1, 3, 3, 5, 5, 7, 9]
Count of 5s :  2


Sorting and Reversing a list

### Question 6
sort and print l3 in ascending and descending order sequentially (given above)

**(Hint: Use .sort() function)**

In [101]:
##Sorting using sort and reverse with sort with reverse flag set as True
print("Sorting Ascending")
l3.sort()
print("Ascending Order",l3)

Sorting Ascending
Ascending Order [0, 1, 2, 3, 3, 4, 5, 5, 6, 7, 8, 9]


In [102]:
print("Sorting Descending")
l3.sort(reverse=True)
print("Descending Order",l3)

Sorting Descending
Descending Order [9, 8, 7, 6, 5, 5, 4, 3, 3, 2, 1, 0]


### Functions

**Example:**

**def** function_name(args)**:**
    
    function code goes here

### Question 7

Define a function with name **sum_3** which can take 3 numbers as input, and returns sum of them.

In [24]:
#sum_3 takes 3 args and returns their sum
def sum_3(num1,num2, num3):
    return num1 + num2 + num3

print("Sum",sum_3(1,2,3))

Sum 6


### Lambda Functions

Anonymous functions or no name functions, which can be considered when you use a function only once.

**Example:**

f = lambda x, y : x + y

f(1,1)

2


### Question 8

Write the same above **sum_3** function using lambda.

In [ ]:
#Rewriting sum_3 as lambda
sum_3 = lambda num1, num2, num3: num1 + num2 + num3

In [25]:
print("sum_3 lambda version",sum_3(3,4,5))

sum_3 lambda version 12


# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding roows, columns, operating on 2d matrices aren't readily available. So, we will use *numpy* for such functions.



In [26]:
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [27]:
l1 = [1,2,3,4]
nd1 = np.array(l1)
print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


Sum functions on np.array()

In [28]:
print(nd2.shape)

print(nd2.size)

print(nd2.dtype)

(2, 4)
8
int32


### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

[ **Hint: ** You can also use **np.identity()** function ]

In [31]:
#Just print an identity array
idarr = np.identity(3)
print("Identity Matrix \n",idarr)

Identity Matrix 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

Use: **np.matrix()** function



In [36]:
#Use matrix and then reshape to generate a 3x3 array
val = [9,8,7,6,5,4,3,2,1]
print('Values :',val)
array1 = np.matrix(val).reshape(3,3)
print('array is: \n',array1)

Values : [9, 8, 7, 6, 5, 4, 3, 2, 1]
array is: 
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


### Question 3

Reverse both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**)

In [37]:
#Reverse the rows and columns
print('Array reverse \n',array1.T)

Array reverse 
 [[9 6 3]
 [8 5 2]
 [7 4 1]]


### Question 4
Add + 1 to all the elements in the given matrix.

In [39]:
#Add 1 to the array using broadcasting
print("Original Array \n",array1)
print("Adding 1 to all elements \n", array1 + 1)

Original Array 
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Adding 1 to all elements 
 [[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]


Similarly you can do operations like scalar  substraction, division, multiplication (operating on each element in the matrix)

### Question 5

Find the mean of all elements in the given matrix nd6.
nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function


In [50]:
#mean of all elements in the given matrix
nd6 = np.array([[ 1, 4, 9, 121, 144, 169], [ 16, 25, 36, 196, 225, 256], [ 49, 64, 81, 289, 324, 361]])
print("nd6 array is \n",nd6)
print("mean is",nd6.mean())

nd6 array is 
 [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
mean is 131.66666666666666


### Question 7

Find the dot product of two given matrices.

[**Hint:** Use **np.dot()**]

In [52]:
#Dot product of teo matrices
print("First Array\n",array1)
print("Second Array\n",nd6)
print("Dot product\n",np.dot(array1,nd6))

First Array
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Second Array
 [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
Dot product
 [[ 480  684  936 4680 5364 6096]
 [ 282  405  558 2862 3285 3738]
 [  84  126  180 1044 1206 1380]]


# Pandas

We have seen Numpy in the last section. It is good at performing math operation on 2d-arrays of numbers. But the major drawback is, it cannot deal with heterogenous values. So, Pandas dataframes are helpful in that aspect for storing different data types and referring the values like a dict in python instead of just referring each item with index.

[Link to Official Documentation](http://pandas.pydata.org/pandas-docs/version/0.23/dsintro.html)

## Series

Pandas series are almost same as nd arrays in numpy, with a additional inferencing ability with custom labels like *keys* in a *dictionary* in python.

In [53]:
import numpy as np
import pandas as pd

In [54]:
#Example

series1 = pd.Series(data = [1,2,3], index = ['key1', 'key2', 'key3'])
series1

key1    1
key2    2
key3    3
dtype: int64

### Question 1

Convert a given dict to pd series.

[**Hint:** Use **.Series**]

In [56]:
d1 = {'a': 1, 'b': 2, 'c': 3}

In [57]:
#Generating series from dict
pd1 = pd.Series(d1)
print("New series\n",pd1)

New series
 a    1
b    2
c    3
dtype: int64


You can directly use numpy functions on series.
### Question 2

Find the dot product of both the series create above


[ **Hint: ** Use **np.dot()** ]

In [62]:
#dot product of two pandas series
print("First Series\n",series1)
print("\n")
print("Second Series\n",pd1)
print("\n")
print("Dot product\n",np.dot(series1,pd1))

First Series
 key1    1
key2    2
key3    3
dtype: int64


Second Series
 a    1
b    2
c    3
dtype: int64


Dot product
 14


## Dataframes

A dataframe is a table with labeled columns which can hold different types of data in each column. 

In [63]:
# Example
d1 = {'a': [1,2,3], 'b': [3,4,5], 'c':[6,7,8] }
df1 = pd.DataFrame(d1)
df1

a  b  c
0  1  3  6
1  2  4  7
2  3  5  8

### Question 3

Select second row in the above dataframe df1.



In [69]:
#Row selection from dataframe
print("Second Row\n")
print(df1.iloc[1])

Second Row

a    2
b    4
c    7
Name: 1, dtype: int64


### Question 4

Select column c in second row of df1.

[ **Hint: ** For using labels use **df.loc[row, column]**. For using numeric indexed use **df.iloc[]**. For using mixture of numeric indexes and labels use **df.ix[row, column]** ]



In [72]:
#Column selection
print("Original DF\n",df1)
print("Column C value\n")
print(df1.iloc[1]["c"])

Original DF
    a  b  c
0  1  3  6
1  2  4  7
2  3  5  8
Column C value

7


## Using Dataframes on a dataset

##### Using the mtcars dataset.

For the below set of questions, we will be using the cars data from [Motor Trend Car Road Tests](http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). 


Details :
    
A data frame with 32 observations on 11 (numeric) variables.

[, 1] 	mpg 	Miles/(US) gallon

[, 2] 	cyl 	Number of cylinders

[, 3] 	disp 	Displacement (cu.in.)

[, 4] 	hp 	Gross horsepower

[, 5] 	drat 	Rear axle ratio

[, 6] 	wt 	Weight (1000 lbs)

[, 7] 	qsec 	1/4 mile time

[, 8] 	vs 	Engine (0 = V-shaped, 1 = straight)

[, 9] 	am 	Transmission (0 = automatic, 1 = manual)

[,10] 	gear 	Number of forward gears

[,11] 	carb 	Number of carburetors 

In [73]:
## Reading a dataset from a csv file using pandas.
mtcars = pd.read_csv('mtcars.csv')
mtcars.index = mtcars['name']


Following questions are based on analysing a particular dataset using dataframes.

### Question 5

Check the type and dimensions of given dataset - mtcars.


[ **Hint: ** Use **type()** and **df.shape** ]

In [84]:
print("Type of mtchars ",type(c))
print("Shape of mtchars",mtcars.shape)
print("Type of mtchars values ", mtcars.dtypes)

Type of mtchars  <class 'pandas.core.frame.DataFrame'>
Shape of mtchars (32, 12)
Type of mtchars values  name     object
mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object


### Question 6

Check the first 10 lines and last 10 lines of the given dataset- mtcars.

[**Hint:** Use **.head()** and **.tail()**]

In [88]:
#Head and Tail of dataframes
print("First 10 lines \n",mtcars.head(10))
print("\n")
print("Last 10 lines \n",mtcars.tail(10))

First 10 lines 
                                 name   mpg  cyl   disp   hp  drat     wt  \
name                                                                       
Mazda RX4                  Mazda RX4  21.0    6  160.0  110  3.90  2.620   
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875   
Datsun 710                Datsun 710  22.8    4  108.0   93  3.85  2.320   
Hornet 4 Drive        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215   
Hornet Sportabout  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440   
Valiant                      Valiant  18.1    6  225.0  105  2.76  3.460   
Duster 360                Duster 360  14.3    8  360.0  245  3.21  3.570   
Merc 240D                  Merc 240D  24.4    4  146.7   62  3.69  3.190   
Merc 230                    Merc 230  22.8    4  140.8   95  3.92  3.150   
Merc 280                    Merc 280  19.2    6  167.6  123  3.92  3.440   

                    qsec  vs  am  gear  carb  
name                   

### Question 7

Print all the column labels in the given dataset - mtcars.

[ **Hint: ** Use **df.columns** ]

In [89]:
#Get all column labels
print("Column names of the dataframe mtcars \n",mtcars.columns)

Column names of the dataframe mtcars 
 Index(['name', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')


### Question 8

Select first 6 rows and 3 columns in mtcars dataframe.

**Hint: **  
mtcars.ix[:,:] gives all rows and columns in the dataset.

In [92]:
#Get the first 6 rows and 3 columns in mtcars
print("Showing the first 6 rows and 3 columns \n")
print(mtcars.ix[:7,:4])

Showing the first 6 rows and 3 columns 

                                name   mpg  cyl   disp
name                                                  
Mazda RX4                  Mazda RX4  21.0    6  160.0
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6  160.0
Datsun 710                Datsun 710  22.8    4  108.0
Hornet 4 Drive        Hornet 4 Drive  21.4    6  258.0
Hornet Sportabout  Hornet Sportabout  18.7    8  360.0
Valiant                      Valiant  18.1    6  225.0
Duster 360                Duster 360  14.3    8  360.0


C:\Users\rejimonr\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until
