# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
#%tensorflow_version 2.x
#Running code locally with only TF 2

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.0.0'

### Set random seed

In [4]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [5]:
#Load the required basic libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
#Load the iris dataset from sklearn library
from sklearn.datasets import load_iris
iris = load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [7]:
#Get features and labels
features = iris.data
labels = iris.target

In [8]:
#check the dataset dimensions
features.shape
#4 features

(150, 4)

In [9]:
#target dimensions
labels.shape

(150,)

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [10]:
#Import from sklearn
from sklearn.model_selection import train_test_split

In [11]:
#Initialize seed and test size
seed = 10
test_split = 0.25

In [12]:
#Split into test, train
X_train, X_test, y_train, y_test = train_test_split(features,labels,test_size=test_split,random_state=seed)

In [13]:
#check the training and testing dataset shapes
print("Training features :",X_train.shape)
print("Training labels :",y_train.shape)
print("Test features :",X_test.shape)
print("Test labels :",y_test.shape)

Training features : (112, 4)
Training labels : (112,)
Test features : (38, 4)
Test labels : (38,)


## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [14]:
#import from sklearn
from sklearn.preprocessing import OneHotEncoder

In [15]:
#Initialize with sparse False as the records are small in number
ohe = OneHotEncoder(sparse=False)

In [16]:
#Check the data type
y_train.dtype

dtype('int32')

In [17]:
#fit and transform y_train. Reshape to avoid ohe limitation in handling single column in itself
y_train = ohe.fit_transform(y_train.reshape(-1,1))

In [18]:
#Transform y_test also
y_test = ohe.transform(y_test.reshape(-1,1))

In [19]:
#check the shape of y now after one hot encoding
print("Training Labels :",y_train.shape)
print("Test labels :",y_test.shape)

#As expected it has became 3 colums now

Training Labels : (112, 3)
Test labels : (38, 3)


## Question 5

### Initialize a sequential model
- Define a sequential model

In [20]:
import tensorflow.keras as keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [21]:
#Initialize the model
model = Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [22]:
#Add a dense layer with softmax function. This will serve as the i/p and o/p layer
model.add(Dense(3,activation='softmax',input_shape=(4,)))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [23]:
#Compile the model
model.compile(loss="categorical_crossentropy",optimizer="SGD",metrics=["accuracy"])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [24]:
#use summary to understand the model
model.summary()

#We can see that we have 15 parameters which needs to be trained which is basically the weights and biases

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [25]:
#Lets train the model now
history = model.fit(X_train, y_train,epochs=100, batch_size=1, verbose=1)

Train on 112 samples
Epoch 1/100
112/112 [==============================] - 0s 4ms/sample - loss: 1.1600 - accuracy: 0.4018
Epoch 2/100
112/112 [==============================] - 0s 757us/sample - loss: 0.6852 - accuracy: 0.7321
Epoch 3/100
112/112 [==============================] - 0s 764us/sample - loss: 0.5749 - accuracy: 0.7411
Epoch 4/100
112/112 [==============================] - 0s 757us/sample - loss: 0.5172 - accuracy: 0.7589
Epoch 5/100
112/112 [==============================] - 0s 769us/sample - loss: 0.4916 - accuracy: 0.7589
Epoch 6/100
112/112 [==============================] - 0s 754us/sample - loss: 0.4298 - accuracy: 0.8125
Epoch 7/100
112/112 [==============================] - 0s 793us/sample - loss: 0.4226 - accuracy: 0.8393
Epoch 8/100
112/112 [==============================] - 0s 754us/sample - loss: 0.4129 - accuracy: 0.8125
Epoch 9/100
112/112 [==============================] - 0s 773us/sample - loss: 0.3825 - accuracy: 0.8214
Epoch 10/100
112/112 [==============

112/112 [==============================] - 0s 734us/sample - loss: 0.1413 - accuracy: 0.9821
Epoch 79/100
112/112 [==============================] - 0s 748us/sample - loss: 0.1412 - accuracy: 0.9643
Epoch 80/100
112/112 [==============================] - 0s 741us/sample - loss: 0.1424 - accuracy: 0.9643
Epoch 81/100
112/112 [==============================] - 0s 726us/sample - loss: 0.1436 - accuracy: 0.9732
Epoch 82/100
112/112 [==============================] - 0s 748us/sample - loss: 0.1382 - accuracy: 0.9643
Epoch 83/100
112/112 [==============================] - 0s 854us/sample - loss: 0.1375 - accuracy: 0.9643
Epoch 84/100
112/112 [==============================] - 0s 893us/sample - loss: 0.1435 - accuracy: 0.9732
Epoch 85/100
112/112 [==============================] - 0s 865us/sample - loss: 0.1350 - accuracy: 0.9732
Epoch 86/100
112/112 [==============================] - 0s 715us/sample - loss: 0.1412 - accuracy: 0.9643
Epoch 87/100
112/112 [==============================] - 0s 

## Question 10

### Make predictions
- Predict labels on one row

In [27]:
#Lets predict for the first row
#Get all the predictions

y_pred = np.round(model.predict(X_test))

In [28]:
#Get the prediction of the first row
y_pred[0]

array([0., 1., 0.], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [29]:
#Get the actual of the first row
y_test[0]

#The prediction and actuals are matchine in this case

array([0., 1., 0.])

In [30]:
#Check the overall accuracy again for reference
print(model.evaluate(X_test,y_test,verbose=0))

[0.12544920805253482, 0.9736842]




---



In [52]:
##Just for comparison build another model with one i/p, hidden layer, o/p layer
model_second = Sequential()

In [53]:
#Input layer giving out 4 outputs
model_second.add(Dense(4,activation='softmax',input_shape=(4,)))

In [54]:
#Add another Dense layer and giving another output of 4 with relu as activation function
model_second.add(Dense(4,activation="relu"))

In [55]:
#Final output layer with softmax function
model_second.add(Dense(3,activation="softmax"))

In [56]:
#Compile the model
model_second.compile(loss="categorical_crossentropy",optimizer="SGD",metrics=["accuracy"])

In [57]:
#Check the model summary
model_second.summary()

#We can see the trainable parameters went up to 55

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 4)                 20        
_________________________________________________________________
dense_13 (Dense)             (None, 4)                 20        
_________________________________________________________________
dense_14 (Dense)             (None, 3)                 15        
Total params: 55
Trainable params: 55
Non-trainable params: 0
_________________________________________________________________


In [58]:
#Lets train the model now
history = model_second.fit(X_train, y_train,epochs=100, batch_size=1, verbose=1)


Train on 112 samples
Epoch 1/100
112/112 [==============================] - 0s 2ms/sample - loss: 1.1119 - accuracy: 0.2589
Epoch 2/100
112/112 [==============================] - 0s 774us/sample - loss: 1.1022 - accuracy: 0.2857
Epoch 3/100
112/112 [==============================] - 0s 768us/sample - loss: 1.0934 - accuracy: 0.3571
Epoch 4/100
112/112 [==============================] - 0s 817us/sample - loss: 1.0786 - accuracy: 0.4107
Epoch 5/100
112/112 [==============================] - 0s 808us/sample - loss: 1.0492 - accuracy: 0.5268
Epoch 6/100
112/112 [==============================] - 0s 829us/sample - loss: 0.9903 - accuracy: 0.5625
Epoch 7/100
112/112 [==============================] - 0s 811us/sample - loss: 0.8974 - accuracy: 0.5982
Epoch 8/100
112/112 [==============================] - 0s 895us/sample - loss: 0.7819 - accuracy: 0.6429
Epoch 9/100
112/112 [==============================] - 0s 831us/sample - loss: 0.6870 - accuracy: 0.6339
Epoch 10/100
112/112 [==============

112/112 [==============================] - 0s 974us/sample - loss: 0.1907 - accuracy: 0.9286
Epoch 79/100
112/112 [==============================] - 0s 930us/sample - loss: 0.1476 - accuracy: 0.9554
Epoch 80/100
112/112 [==============================] - 0s 952us/sample - loss: 0.2560 - accuracy: 0.9018
Epoch 81/100
112/112 [==============================] - 0s 780us/sample - loss: 0.2768 - accuracy: 0.8929
Epoch 82/100
112/112 [==============================] - 0s 865us/sample - loss: 0.1696 - accuracy: 0.9375
Epoch 83/100
112/112 [==============================] - 0s 950us/sample - loss: 0.2596 - accuracy: 0.8839
Epoch 84/100
112/112 [==============================] - 0s 981us/sample - loss: 0.1903 - accuracy: 0.9286
Epoch 85/100
112/112 [==============================] - 0s 805us/sample - loss: 0.1691 - accuracy: 0.9464
Epoch 86/100
112/112 [==============================] - 0s 758us/sample - loss: 0.2163 - accuracy: 0.9375
Epoch 87/100
112/112 [==============================] - 0s 

# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [59]:
#%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [60]:
#import tensorflow as tf
#print(tf.__version__)

### Set random seed

In [61]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [62]:
# run this cell to upload file if you are using google colab
#from google.colab import files
#files.upload()

In [63]:
#Loading data from local copy of the data set
price_df = pd.read_csv("prices.csv")

#sanity
price_df.head(2)

date symbol        open       close         low        high  \
0  2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998  126.250000   
1  2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002  125.540001   

      volume  
0  2163600.0  
1  2386400.0

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [64]:
#Dropping date and symbol which will not be used
drop_cols = ["date","symbol"]
price_df.drop(drop_cols,axis=1,inplace=True)

#Check columns
price_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 5 columns):
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5)
memory usage: 32.5 MB


## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [65]:
#Get only the first 1000 rows for use now
price_df_base = price_df.copy()
price_df = price_df.head(1000)

In [66]:
#check the dataframe
price_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
open      1000 non-null float64
close     1000 non-null float64
low       1000 non-null float64
high      1000 non-null float64
volume    1000 non-null float64
dtypes: float64(5)
memory usage: 39.1 KB


## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [71]:
#Seperate the features and targets
y = price_df["volume"]
X = price_df.drop("volume",axis=1)

In [72]:
#sanity
print("X shape :",X.shape)
print("labels shape:",y.shape)

X shape : (1000, 4)
labels shape: (1000,)


In [73]:
#Lets normalize the volume by dividing by 1000000
y = y/1000000

#sanity
y[0]

2.1636

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [74]:
#Convert to numpy array
X_np = X.to_numpy(dtype="float32")
y_np = y.to_numpy(dtype="float32")

In [75]:
#sanity check
X_np.shape

(1000, 4)

In [76]:
y_np.shape

(1000,)

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [77]:
#Normalize features
X_np = tf.math.l2_normalize(X_np)

In [78]:
#check sanity
X_np.shape

TensorShape([1000, 4])

In [81]:
#check one row
X_np[0].numpy()

array([0.02202894, 0.02245906, 0.02182905, 0.02253223], dtype=float32)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [82]:
#Lets initialize the weights and biases
W = tf.zeros(shape=[4,1])
b = tf.zeros(shape=[1])

In [83]:
#Check weights and bias are zeros
print("Initial weights",W.numpy())
print("Initial bias",b.numpy())

Initial weights [[0.]
 [0.]
 [0.]
 [0.]]
Initial bias [0.]


## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [84]:
#Will take each X value and get an output prediction
def predictionfn(X,W,b):
    y_hat = tf.add(tf.matmul(X,W),b)
    return y_hat

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [85]:
#Loss function
def lossfn(y,y_hat):
    error = tf.subtract(y_hat,y)
    loss = tf.reduce_mean(tf.square(error))
    return loss

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [86]:
#We will use the prediction and loss function to train
def trainfn(X,y,W,b,learning_rate=0.01):
    
    with tf.GradientTape() as tape:
        tape.watch([W,b])
        
        #forward pass
        y_hat = predictionfn(X,W,b)

        #calculate loss
        current_loss = lossfn(y,y_hat)

        #evalute the gradient with the respect to the paramters
        dW, db = tape.gradient(current_loss, [W, b])

        #update the paramters using Gradient Descent
        W = W - dW * learning_rate
        b = b - db* learning_rate
        
        #return updated weights and bias
        return W,b, current_loss
        

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [87]:
#Lets run the training for 100
train_steps = 100

In [88]:
#Run the iteration

for i in range(train_steps):
    W, b, loss = trainfn(X_np,y_np,W,b)
    print(f'Iteration {i}, current loss {loss} ')

Iteration 0, current loss 237.28665161132812 
Iteration 1, current loss 236.16758728027344 
Iteration 2, current loss 235.09298706054688 
Iteration 3, current loss 234.06101989746094 
Iteration 4, current loss 233.06997680664062 
Iteration 5, current loss 232.11782836914062 
Iteration 6, current loss 231.2038116455078 
Iteration 7, current loss 230.32586669921875 
Iteration 8, current loss 229.48265075683594 
Iteration 9, current loss 228.67298889160156 
Iteration 10, current loss 227.89537048339844 
Iteration 11, current loss 227.1483154296875 
Iteration 12, current loss 226.43113708496094 
Iteration 13, current loss 225.7423553466797 
Iteration 14, current loss 225.08079528808594 
Iteration 15, current loss 224.4455108642578 
Iteration 16, current loss 223.83502197265625 
Iteration 17, current loss 223.2493133544922 
Iteration 18, current loss 222.6865692138672 
Iteration 19, current loss 222.1459503173828 
Iteration 20, current loss 221.6268768310547 
Iteration 21, current loss 221.

### Observe values of Weight
- Print the updated values

In [89]:
#Updated weights after 100 iterations
print(W.numpy())

[[0.05478281]
 [0.05488191]
 [0.05422735]
 [0.05533117]]


### Observe values of Bias
- Print the updated values

In [90]:
#Updated bias after 100 iterations
print(b.numpy())

[4.607657]
